// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AccountBalance struct {
	Trader                   string `json:"trader"`
	PrimaryCredit            string `json:"primaryCredit"`            // 主资产余额（链上 + 链下合计）
	OnChainPrimaryCredit     string `json:"onChainPrimaryCredit"`     // Dealer 链上 credit
	LedgerPrimaryBalance     string `json:"ledgerPrimaryBalance"`     // Treasury 扫链累计 ledger
	SecondaryCredit          string `json:"secondaryCredit"`          // 次级资产余额
	PendingPrimaryWithdraw   string `json:"pendingPrimaryWithdraw"`   // 待取款主资产
	PendingSecondaryWithdraw string `json:"pendingSecondaryWithdraw"` // 待取款次级资产
	ExecutionTimestamp       int64  `json:"executionTimestamp"`       // 可执行取款时间
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CancelOrderReq struct {
	OrderId   string `json:"orderId"`
	Signer    string `json:"signer"`
	Signature string `json:"signature"` // 取消签名
}

type CancelOrderResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CreateOrderReq struct {
	Perp         string `json:"perp"`
	Signer       string `json:"signer"`
	PaperAmount  string `json:"paperAmount"`
	CreditAmount string `json:"creditAmount"`
	MakerFeeRate string `json:"makerFeeRate"`
	TakerFeeRate string `json:"takerFeeRate"`
	Expiration   int64  `json:"expiration"`
	Nonce        int64  `json:"nonce"`
	Signature    string `json:"signature"`
}

type CreateOrderResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	OrderId string `json:"orderId"`
}

type DepositRecord struct {
	TxHash          string `json:"txHash"`
	Trader          string `json:"trader"`
	PrimaryAmount   string `json:"primaryAmount"`
	SecondaryAmount string `json:"secondaryAmount"`
	BlockNumber     int64  `json:"blockNumber"`
	CreateTime      int64  `json:"createTime"`
}

type FundingRateRecord struct {
	Perp       string `json:"perp"`
	Rate       string `json:"rate"`
	MarkPrice  string `json:"markPrice"`
	IndexPrice string `json:"indexPrice"`
	SettleTime int64  `json:"settleTime"`
}

type GetBalanceReq struct {
	Trader string `form:"trader"`
}

type GetBalanceResp struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Balance AccountBalance `json:"balance"`
}

type GetKlinesReq struct {
	Perp      string `form:"perp"`
	Interval  string `form:"interval"` // 1m, 5m, 15m, 1h, 4h, 1d
	StartTime int64  `form:"startTime,optional"`
	EndTime   int64  `form:"endTime,optional"`
	Limit     int    `form:"limit,default=100"`
}

type GetKlinesResp struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	Klines  []Kline `json:"klines"`
}

type GetMarketReq struct {
	Address string `path:"address"`
}

type GetMarketResp struct {
	Code    int        `json:"code"`
	Message string     `json:"message"`
	Market  PerpMarket `json:"market"`
}

type GetOrderBookReq struct {
	Perp  string `form:"perp"`
	Limit int    `form:"limit,default=20"`
}

type GetOrderBookResp struct {
	Code    int              `json:"code"`
	Message string           `json:"message"`
	Bids    []OrderBookEntry `json:"bids"` // 买单
	Asks    []OrderBookEntry `json:"asks"` // 卖单
}

type GetOrderReq struct {
	OrderId string `path:"orderId"`
}

type GetOrderResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Order   Order  `json:"order"`
}

type GetPositionsReq struct {
	Trader string `form:"trader"`
}

type GetPositionsResp struct {
	Code      int        `json:"code"`
	Message   string     `json:"message"`
	Positions []Position `json:"positions"`
}

type GetRiskInfoReq struct {
	Trader string `form:"trader"`
}

type GetRiskInfoResp struct {
	Code     int      `json:"code"`
	Message  string   `json:"message"`
	RiskInfo RiskInfo `json:"riskInfo"`
}

type GetTickerReq struct {
	Perp string `form:"perp,optional"` // 为空时返回所有
}

type GetTickerResp struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Tickers []Ticker `json:"tickers"`
}

type Kline struct {
	Time   int64  `json:"time"`
	Open   string `json:"open"`
	High   string `json:"high"`
	Low    string `json:"low"`
	Close  string `json:"close"`
	Volume string `json:"volume"`
}

type LiquidationRecord struct {
	TxHash           string `json:"txHash"`
	Perp             string `json:"perp"`
	Liquidator       string `json:"liquidator"`
	LiquidatedTrader string `json:"liquidatedTrader"`
	PaperChange      string `json:"paperChange"`
	CreditChange     string `json:"creditChange"`
	InsuranceFee     string `json:"insuranceFee"`
	BlockNumber      int64  `json:"blockNumber"`
	CreateTime       int64  `json:"createTime"`
}

type ListDepositsReq struct {
	Trader   string `form:"trader"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListDepositsResp struct {
	Code     int             `json:"code"`
	Message  string          `json:"message"`
	Deposits []DepositRecord `json:"deposits"`
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"pageSize"`
}

type ListFundingRatesReq struct {
	Perp     string `form:"perp"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListFundingRatesResp struct {
	Code         int                 `json:"code"`
	Message      string              `json:"message"`
	FundingRates []FundingRateRecord `json:"fundingRates"`
	Total        int64               `json:"total"`
	Page         int                 `json:"page"`
	PageSize     int                 `json:"pageSize"`
}

type GetLatestFundingRateReq struct {
	Perp string `form:"perp"`
}

// FundingRateLatest 当前合约资金费展示（当期费率 + 下期结算倒计时锚点）。
type FundingRateLatest struct {
	Perp                   string `json:"perp"`
	PeriodRatePct          string `json:"periodRatePct"`          // 上期/当期费率，如 0.0123 表示 0.0123%
	PeriodRateSource       string `json:"periodRateSource"`       // last_settle | predicted
	PredictedPeriodRatePct string `json:"predictedPeriodRatePct"` // 按当前 mark/index 预估下期
	CumulativeRate         string `json:"cumulativeRate"`         // 链上累计资金指数
	LastSettleAt           int64  `json:"lastSettleAt"`           // 上次结算 Unix 秒，无记录为 0
	NextSettleAt           int64  `json:"nextSettleAt"`           // 下次结算 Unix 秒
	SettleIntervalSec      int    `json:"settleIntervalSec"`
	SettleSchedule         string `json:"settleSchedule"`
}

type GetLatestFundingRateResp struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Latest  FundingRateLatest  `json:"latest"`
}

type ListLiquidationsReq struct {
	Trader   string `form:"trader,optional"` // 为空时返回所有
	Perp     string `form:"perp,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListLiquidationsResp struct {
	Code         int                 `json:"code"`
	Message      string              `json:"message"`
	Liquidations []LiquidationRecord `json:"liquidations"`
	Total        int64               `json:"total"`
	Page         int                 `json:"page"`
	PageSize     int                 `json:"pageSize"`
}

type ListMarketsReq struct {
}

type ListMarketsResp struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Markets []PerpMarket `json:"markets"`
}

type ListOrdersReq struct {
	Signer   string `form:"signer"`
	Perp     string `form:"perp,optional"`
	Status   int    `form:"status,optional,default=-1"` // -1表示全部
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListOrdersResp struct {
	Code     int     `json:"code"`
	Message  string  `json:"message"`
	Orders   []Order `json:"orders"`
	Total    int64   `json:"total"`
	Page     int     `json:"page"`
	PageSize int     `json:"pageSize"`
}

type ListTradesReq struct {
	Trader   string `form:"trader,optional"`
	Perp     string `form:"perp,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListTradesResp struct {
	Code     int     `json:"code"`
	Message  string  `json:"message"`
	Trades   []Trade `json:"trades"`
	Total    int64   `json:"total"`
	Page     int     `json:"page"`
	PageSize int     `json:"pageSize"`
}

type ListWithdrawsReq struct {
	Trader   string `form:"trader"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ListWithdrawsResp struct {
	Code      int              `json:"code"`
	Message   string           `json:"message"`
	Withdraws []WithdrawRecord `json:"withdraws"`
	Total     int64            `json:"total"`
	Page      int              `json:"page"`
	PageSize  int              `json:"pageSize"`
}

type Order struct {
	OrderId      string `json:"orderId"`
	Perp         string `json:"perp"`         // 永续合约地址
	Signer       string `json:"signer"`       // 签名者地址
	PaperAmount  string `json:"paperAmount"`  // 仓位数量
	CreditAmount string `json:"creditAmount"` // 资金数量
	MakerFeeRate string `json:"makerFeeRate"` // Maker 手续费率
	TakerFeeRate string `json:"takerFeeRate"` // Taker 手续费率
	Expiration   int64  `json:"expiration"`   // 过期时间
	Nonce        int64  `json:"nonce"`        // 随机数
	Signature    string `json:"signature"`    // EIP-712 签名
	Status       int    `json:"status"`       // 状态: 0-待处理, 1-部分成交, 2-完全成交, 3-已取消
	FilledAmount string `json:"filledAmount"` // 已成交数量
	CreateTime   int64  `json:"createTime"`
	UpdateTime   int64  `json:"updateTime"`
}

type OrderBookEntry struct {
	Price  string `json:"price"`
	Amount string `json:"amount"`
}

type PageReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type PageResp struct {
	Total    int64 `json:"total"`
	Page     int   `json:"page"`
	PageSize int   `json:"pageSize"`
}

type PerpMarket struct {
	Address              string `json:"address"`
	Name                 string `json:"name"`
	InitialMarginRatio   string `json:"initialMarginRatio"`   // 初始保证金率（1e18 原始值）
	InitialMarginPct     string `json:"initialMarginPct"`     // 初始保证金率 %，如 5.00
	MaxLeverage          string `json:"maxLeverage"`          // 最大杠杆倍数，如 20
	LiquidationThreshold string `json:"liquidationThreshold"` // 维持保证金率（1e18 原始值）
	MaintenanceMarginPct string `json:"maintenanceMarginPct"` // 维持保证金率 %，如 3.00
	LiquidationPriceOff  string `json:"liquidationPriceOff"`  // 清算折扣
	InsuranceFeeRate     string `json:"insuranceFeeRate"`     // 保险费率
	MarkPrice            string `json:"markPrice"`            // 标记价格
	IndexPrice           string `json:"indexPrice"`           // 指数价格
	FundingRate          string `json:"fundingRate"`          // 资金费率
	OpenInterest         string `json:"openInterest"`         // 持仓量
	Volume24h            string `json:"volume24h"`            // 24小时成交量
	IsRegistered         bool   `json:"isRegistered"`
}

type Position struct {
	Trader        string `json:"trader"`
	Perp          string `json:"perp"`
	PerpName      string `json:"perpName"`
	Paper         string `json:"paper"`         // 仓位数量
	Credit        string `json:"credit"`        // 资金数量
	EntryPrice    string `json:"entryPrice"`    // 开仓均价
	MarkPrice     string `json:"markPrice"`     // 标记价格
	UnrealizedPnl string `json:"unrealizedPnl"` // 未实现盈亏
	Leverage      string `json:"leverage"`      // 杠杆倍数
	LiqPrice      string `json:"liqPrice"`      // 清算价格
	UpdateTime    int64  `json:"updateTime"`
}

type RiskInfo struct {
	Trader            string `json:"trader"`
	NetValue          string `json:"netValue"`          // 净值
	Exposure          string `json:"exposure"`          // 敞口
	MaintenanceMargin string `json:"maintenanceMargin"` // 维持保证金
	AvailableMargin   string `json:"availableMargin"`   // 可用保证金
	MarginRatio       string `json:"marginRatio"`       // 保证金率
	IsSafe            bool   `json:"isSafe"`            // 是否安全
}

type Ticker struct {
	Perp               string `json:"perp"`
	Price              string `json:"price"`
	PriceChange        string `json:"priceChange"`
	PriceChangePercent string `json:"priceChangePercent"`
	High24h            string `json:"high24h"`
	Low24h             string `json:"low24h"`
	Volume24h          string `json:"volume24h"`
	UpdateTime         int64  `json:"updateTime"`
}

type Trade struct {
	TradeId      string `json:"tradeId"`
	Perp         string `json:"perp"`
	TakerOrderId string `json:"takerOrderId"`
	MakerOrderId string `json:"makerOrderId"`
	Taker        string `json:"taker"`
	Maker        string `json:"maker"`
	PaperAmount  string `json:"paperAmount"`
	Price        string `json:"price"`
	TakerFee     string `json:"takerFee"`
	MakerFee     string `json:"makerFee"`
	TxHash       string `json:"txHash"`
	BlockNumber  int64  `json:"blockNumber"`
	CreateTime   int64  `json:"createTime"`
}

type WithdrawRecord struct {
	TxHash          string `json:"txHash"`
	Trader          string `json:"trader"`
	PrimaryAmount   string `json:"primaryAmount"`
	SecondaryAmount string `json:"secondaryAmount"`
	Status          int    `json:"status"` // 0-待处理, 1-已完成, 2-已取消
	BlockNumber     int64  `json:"blockNumber"`
	CreateTime      int64  `json:"createTime"`
}

// ---------- 钱包签名登录 ----------

type AuthNonceReq struct {
	Address string `json:"address"`
}

type AuthNonceResp struct {
	Code          int    `json:"code"`
	Message       string `json:"message"`
	Nonce         string `json:"nonce,omitempty"`
	MessageToSign string `json:"messageToSign,omitempty"`
}

type AuthVerifyReq struct {
	Address   string `json:"address"`
	Message   string `json:"message"`
	Signature string `json:"signature"`
}

type AuthVerifyResp struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	Token     string `json:"token,omitempty"`
	ExpiresAt int64  `json:"expiresAt,omitempty"`
	UserId    string `json:"userId,omitempty"`
	Wallet    string `json:"wallet,omitempty"`
}

// GetOpenQuoteReq 开仓系统参考价（无需用户自填限价）。
type GetOpenQuoteReq struct {
	Perp string `form:"perp"`
	Side string `form:"side"` // long | short
}

type OpenQuote struct {
	Perp       string `json:"perp"`
	Side       string `json:"side"`
	PriceUsd   string `json:"priceUsd"`   // 2 位小数，用于展示与下单
	PriceRaw   string `json:"priceRaw"`   // 1e6 整数串，与 paper/credit 一致
	Source     string `json:"source"`     // best_ask | best_bid | orderbook_mid | chain_mark | spot_index
	BestBid    string `json:"bestBid"`
	BestAsk    string `json:"bestAsk"`
	MarkPrice  string `json:"markPrice"`
	IndexPrice string `json:"indexPrice"`
}

type GetOpenQuoteResp struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Quote   OpenQuote `json:"quote"`
}
