// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	account "metanode/internal/handler/account"
	funding "metanode/internal/handler/funding"
	liquidation "metanode/internal/handler/liquidation"
	market "metanode/internal/handler/market"
	order "metanode/internal/handler/order"
	position "metanode/internal/handler/position"
	trade "metanode/internal/handler/trade"
	"metanode/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/nonce",
				Handler: AuthNonceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/verify",
				Handler: AuthVerifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询账户余额
				Method:  http.MethodGet,
				Path:    "/balance",
				Handler: account.GetBalanceHandler(serverCtx),
			},
			{
				// 查询存款记录
				Method:  http.MethodGet,
				Path:    "/deposits",
				Handler: account.ListDepositsHandler(serverCtx),
			},
			{
				// 查询取款记录
				Method:  http.MethodGet,
				Path:    "/withdraws",
				Handler: account.ListWithdrawsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取资金费率历史
				Method:  http.MethodGet,
				Path:    "/funding-rates",
				Handler: funding.ListFundingRatesHandler(serverCtx),
			},
			{
				// 当前合约资金费率与下期结算时间
				Method:  http.MethodGet,
				Path:    "/funding-rate/latest",
				Handler: funding.GetLatestFundingRateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取清算记录
				Method:  http.MethodGet,
				Path:    "/liquidations",
				Handler: liquidation.ListLiquidationsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取K线数据
				Method:  http.MethodGet,
				Path:    "/klines",
				Handler: market.GetKlinesHandler(serverCtx),
			},
			{
				// 获取所有市场
				Method:  http.MethodGet,
				Path:    "/markets",
				Handler: market.ListMarketsHandler(serverCtx),
			},
			{
				// 获取市场详情
				Method:  http.MethodGet,
				Path:    "/markets/:address",
				Handler: market.GetMarketHandler(serverCtx),
			},
			{
				// 开仓参考价（做多卖一/做空买一）
				Method:  http.MethodGet,
				Path:    "/open-quote",
				Handler: market.GetOpenQuoteHandler(serverCtx),
			},
			{
				// 获取深度
				Method:  http.MethodGet,
				Path:    "/orderbook",
				Handler: market.GetOrderBookHandler(serverCtx),
			},
			{
				// 获取行情
				Method:  http.MethodGet,
				Path:    "/ticker",
				Handler: market.GetTickerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 查询订单列表
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: order.ListOrdersHandler(serverCtx),
			},
			{
				// 查询订单
				Method:  http.MethodGet,
				Path:    "/orders/:orderId",
				Handler: order.GetOrderHandler(serverCtx),
			},
			{
				// 取消订单
				Method:  http.MethodPost,
				Path:    "/orders/cancel",
				Handler: order.CancelOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询用户仓位
				Method:  http.MethodGet,
				Path:    "/positions",
				Handler: position.GetPositionsHandler(serverCtx),
			},
			{
				// 查询风险信息
				Method:  http.MethodGet,
				Path:    "/risk",
				Handler: position.GetRiskInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询成交记录
				Method:  http.MethodGet,
				Path:    "/trades",
				Handler: trade.ListTradesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
